package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"

	"github.com/twiglab/crm/member/orm"
	"github.com/twiglab/crm/member/pkg/data"
)

// QryMemberByCode is the resolver for the qryMemberByCode field.
func (r *queryResolver) QryMemberByCode(ctx context.Context, input data.CodeReq) (*data.MemberResp, error) {
	mb, err := r.Op.GetMemberByCode(ctx, orm.Param{Code: input.Code})
	if err != nil {
		return nil, err
	}
	return &data.MemberResp{
		Code:     mb.Code,
		Level:    mb.Level,
		WxOpenID: mb.WxOpenID,
		Status:   mb.Status,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
