// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BalanceDetailResp struct {
	MemberCode string `json:"memberCode"`
	Balance    int    `json:"balance"`
}

type BalanceReq struct {
	MemberCode string `json:"memberCode"`
}

type BonusItem struct {
	Code       string `json:"code"`
	MemberCode string `json:"memberCode"`
	MallCode   string `json:"mallCode"`
	MallName   string `json:"mallName"`
	ShopCode   string `json:"shopCode"`
	ShopName   string `json:"shopName"`
	Amount     int    `json:"amount"`
	Bonus      int    `json:"bonus"`
}

type BonusPageReq struct {
	MemberCode string `json:"memberCode"`
	Last       string `json:"last"`
	Limit      int32  `json:"limit"`
}

type BonusPageResp struct {
	BonusItems []*BonusItem `json:"bonusItems"`
	Last       string       `json:"last"`
	Limit      int32        `json:"limit"`
}

type Query struct {
}
