// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package low

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/twiglab/crm/wechat/pkg/sns"
)

// AuthUserResponse is returned by AuthUser on success.
type AuthUserResponse struct {
	AuthUser sns.AuthUserResp `json:"authUser"`
}

// GetAuthUser returns AuthUserResponse.AuthUser, and is useful for accessing the field via an interface.
func (v *AuthUserResponse) GetAuthUser() sns.AuthUserResp { return v.AuthUser }

// __AuthUserInput is used internally by genqlient
type __AuthUserInput struct {
	Input sns.JsCodeReq `json:"input"`
}

// GetInput returns __AuthUserInput.Input, and is useful for accessing the field via an interface.
func (v *__AuthUserInput) GetInput() sns.JsCodeReq { return v.Input }

// The query or mutation executed by AuthUser.
const AuthUser_Operation = `
query AuthUser ($input: JsCodeReq!) {
	authUser(input: $input) {
		openID
		unionID
	}
}
`

func AuthUser(
	ctx_ context.Context,
	client_ graphql.Client,
	input sns.JsCodeReq,
) (*AuthUserResponse, error) {
	req_ := &graphql.Request{
		OpName: "AuthUser",
		Query:  AuthUser_Operation,
		Variables: &__AuthUserInput{
			Input: input,
		},
	}
	var err_ error

	var data_ AuthUserResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
