// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/crm/poly/orm/ent/poly"
)

// PolyCreate is the builder for creating a Poly entity.
type PolyCreate struct {
	config
	mutation *PolyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (pc *PolyCreate) SetCode(s string) *PolyCreate {
	pc.mutation.SetCode(s)
	return pc
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (pc *PolyCreate) SetNillableCode(s *string) *PolyCreate {
	if s != nil {
		pc.SetCode(*s)
	}
	return pc
}

// SetMallCode sets the "mall_code" field.
func (pc *PolyCreate) SetMallCode(s string) *PolyCreate {
	pc.mutation.SetMallCode(s)
	return pc
}

// SetRuleCode sets the "rule_code" field.
func (pc *PolyCreate) SetRuleCode(s string) *PolyCreate {
	pc.mutation.SetRuleCode(s)
	return pc
}

// SetName sets the "name" field.
func (pc *PolyCreate) SetName(s string) *PolyCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetDesc sets the "desc" field.
func (pc *PolyCreate) SetDesc(s string) *PolyCreate {
	pc.mutation.SetDesc(s)
	return pc
}

// SetStartTime sets the "start_time" field.
func (pc *PolyCreate) SetStartTime(t time.Time) *PolyCreate {
	pc.mutation.SetStartTime(t)
	return pc
}

// SetEndTime sets the "end_time" field.
func (pc *PolyCreate) SetEndTime(t time.Time) *PolyCreate {
	pc.mutation.SetEndTime(t)
	return pc
}

// SetStatus sets the "status" field.
func (pc *PolyCreate) SetStatus(i int) *PolyCreate {
	pc.mutation.SetStatus(i)
	return pc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pc *PolyCreate) SetNillableStatus(i *int) *PolyCreate {
	if i != nil {
		pc.SetStatus(*i)
	}
	return pc
}

// SetType sets the "type" field.
func (pc *PolyCreate) SetType(i int) *PolyCreate {
	pc.mutation.SetType(i)
	return pc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (pc *PolyCreate) SetNillableType(i *int) *PolyCreate {
	if i != nil {
		pc.SetType(*i)
	}
	return pc
}

// Mutation returns the PolyMutation object of the builder.
func (pc *PolyCreate) Mutation() *PolyMutation {
	return pc.mutation
}

// Save creates the Poly in the database.
func (pc *PolyCreate) Save(ctx context.Context) (*Poly, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PolyCreate) SaveX(ctx context.Context) *Poly {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PolyCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PolyCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PolyCreate) defaults() {
	if _, ok := pc.mutation.Code(); !ok {
		v := poly.DefaultCode()
		pc.mutation.SetCode(v)
	}
	if _, ok := pc.mutation.Status(); !ok {
		v := poly.DefaultStatus
		pc.mutation.SetStatus(v)
	}
	if _, ok := pc.mutation.GetType(); !ok {
		v := poly.DefaultType
		pc.mutation.SetType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PolyCreate) check() error {
	if _, ok := pc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Poly.code"`)}
	}
	if v, ok := pc.mutation.Code(); ok {
		if err := poly.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Poly.code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.MallCode(); !ok {
		return &ValidationError{Name: "mall_code", err: errors.New(`ent: missing required field "Poly.mall_code"`)}
	}
	if v, ok := pc.mutation.MallCode(); ok {
		if err := poly.MallCodeValidator(v); err != nil {
			return &ValidationError{Name: "mall_code", err: fmt.Errorf(`ent: validator failed for field "Poly.mall_code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.RuleCode(); !ok {
		return &ValidationError{Name: "rule_code", err: errors.New(`ent: missing required field "Poly.rule_code"`)}
	}
	if v, ok := pc.mutation.RuleCode(); ok {
		if err := poly.RuleCodeValidator(v); err != nil {
			return &ValidationError{Name: "rule_code", err: fmt.Errorf(`ent: validator failed for field "Poly.rule_code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Poly.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := poly.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Poly.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Poly.desc"`)}
	}
	if v, ok := pc.mutation.Desc(); ok {
		if err := poly.DescValidator(v); err != nil {
			return &ValidationError{Name: "desc", err: fmt.Errorf(`ent: validator failed for field "Poly.desc": %w`, err)}
		}
	}
	if _, ok := pc.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Poly.start_time"`)}
	}
	if _, ok := pc.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "Poly.end_time"`)}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Poly.status"`)}
	}
	if _, ok := pc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Poly.type"`)}
	}
	return nil
}

func (pc *PolyCreate) sqlSave(ctx context.Context) (*Poly, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PolyCreate) createSpec() (*Poly, *sqlgraph.CreateSpec) {
	var (
		_node = &Poly{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(poly.Table, sqlgraph.NewFieldSpec(poly.FieldID, field.TypeInt))
	)
	_spec.OnConflict = pc.conflict
	if value, ok := pc.mutation.Code(); ok {
		_spec.SetField(poly.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := pc.mutation.MallCode(); ok {
		_spec.SetField(poly.FieldMallCode, field.TypeString, value)
		_node.MallCode = value
	}
	if value, ok := pc.mutation.RuleCode(); ok {
		_spec.SetField(poly.FieldRuleCode, field.TypeString, value)
		_node.RuleCode = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(poly.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Desc(); ok {
		_spec.SetField(poly.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := pc.mutation.StartTime(); ok {
		_spec.SetField(poly.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := pc.mutation.EndTime(); ok {
		_spec.SetField(poly.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(poly.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := pc.mutation.GetType(); ok {
		_spec.SetField(poly.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Poly.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PolyUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pc *PolyCreate) OnConflict(opts ...sql.ConflictOption) *PolyUpsertOne {
	pc.conflict = opts
	return &PolyUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Poly.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pc *PolyCreate) OnConflictColumns(columns ...string) *PolyUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &PolyUpsertOne{
		create: pc,
	}
}

type (
	// PolyUpsertOne is the builder for "upsert"-ing
	//  one Poly node.
	PolyUpsertOne struct {
		create *PolyCreate
	}

	// PolyUpsert is the "OnConflict" setter.
	PolyUpsert struct {
		*sql.UpdateSet
	}
)

// SetRuleCode sets the "rule_code" field.
func (u *PolyUpsert) SetRuleCode(v string) *PolyUpsert {
	u.Set(poly.FieldRuleCode, v)
	return u
}

// UpdateRuleCode sets the "rule_code" field to the value that was provided on create.
func (u *PolyUpsert) UpdateRuleCode() *PolyUpsert {
	u.SetExcluded(poly.FieldRuleCode)
	return u
}

// SetName sets the "name" field.
func (u *PolyUpsert) SetName(v string) *PolyUpsert {
	u.Set(poly.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PolyUpsert) UpdateName() *PolyUpsert {
	u.SetExcluded(poly.FieldName)
	return u
}

// SetDesc sets the "desc" field.
func (u *PolyUpsert) SetDesc(v string) *PolyUpsert {
	u.Set(poly.FieldDesc, v)
	return u
}

// UpdateDesc sets the "desc" field to the value that was provided on create.
func (u *PolyUpsert) UpdateDesc() *PolyUpsert {
	u.SetExcluded(poly.FieldDesc)
	return u
}

// SetStartTime sets the "start_time" field.
func (u *PolyUpsert) SetStartTime(v time.Time) *PolyUpsert {
	u.Set(poly.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *PolyUpsert) UpdateStartTime() *PolyUpsert {
	u.SetExcluded(poly.FieldStartTime)
	return u
}

// SetEndTime sets the "end_time" field.
func (u *PolyUpsert) SetEndTime(v time.Time) *PolyUpsert {
	u.Set(poly.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *PolyUpsert) UpdateEndTime() *PolyUpsert {
	u.SetExcluded(poly.FieldEndTime)
	return u
}

// SetStatus sets the "status" field.
func (u *PolyUpsert) SetStatus(v int) *PolyUpsert {
	u.Set(poly.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PolyUpsert) UpdateStatus() *PolyUpsert {
	u.SetExcluded(poly.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *PolyUpsert) AddStatus(v int) *PolyUpsert {
	u.Add(poly.FieldStatus, v)
	return u
}

// SetType sets the "type" field.
func (u *PolyUpsert) SetType(v int) *PolyUpsert {
	u.Set(poly.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *PolyUpsert) UpdateType() *PolyUpsert {
	u.SetExcluded(poly.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *PolyUpsert) AddType(v int) *PolyUpsert {
	u.Add(poly.FieldType, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Poly.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PolyUpsertOne) UpdateNewValues() *PolyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(poly.FieldCode)
		}
		if _, exists := u.create.mutation.MallCode(); exists {
			s.SetIgnore(poly.FieldMallCode)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Poly.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PolyUpsertOne) Ignore() *PolyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PolyUpsertOne) DoNothing() *PolyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PolyCreate.OnConflict
// documentation for more info.
func (u *PolyUpsertOne) Update(set func(*PolyUpsert)) *PolyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PolyUpsert{UpdateSet: update})
	}))
	return u
}

// SetRuleCode sets the "rule_code" field.
func (u *PolyUpsertOne) SetRuleCode(v string) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetRuleCode(v)
	})
}

// UpdateRuleCode sets the "rule_code" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateRuleCode() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateRuleCode()
	})
}

// SetName sets the "name" field.
func (u *PolyUpsertOne) SetName(v string) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateName() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateName()
	})
}

// SetDesc sets the "desc" field.
func (u *PolyUpsertOne) SetDesc(v string) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetDesc(v)
	})
}

// UpdateDesc sets the "desc" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateDesc() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateDesc()
	})
}

// SetStartTime sets the "start_time" field.
func (u *PolyUpsertOne) SetStartTime(v time.Time) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateStartTime() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *PolyUpsertOne) SetEndTime(v time.Time) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateEndTime() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateEndTime()
	})
}

// SetStatus sets the "status" field.
func (u *PolyUpsertOne) SetStatus(v int) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *PolyUpsertOne) AddStatus(v int) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateStatus() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateStatus()
	})
}

// SetType sets the "type" field.
func (u *PolyUpsertOne) SetType(v int) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *PolyUpsertOne) AddType(v int) *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *PolyUpsertOne) UpdateType() *PolyUpsertOne {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *PolyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PolyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PolyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PolyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PolyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PolyCreateBulk is the builder for creating many Poly entities in bulk.
type PolyCreateBulk struct {
	config
	err      error
	builders []*PolyCreate
	conflict []sql.ConflictOption
}

// Save creates the Poly entities in the database.
func (pcb *PolyCreateBulk) Save(ctx context.Context) ([]*Poly, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Poly, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PolyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PolyCreateBulk) SaveX(ctx context.Context) []*Poly {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PolyCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PolyCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Poly.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PolyUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pcb *PolyCreateBulk) OnConflict(opts ...sql.ConflictOption) *PolyUpsertBulk {
	pcb.conflict = opts
	return &PolyUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Poly.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pcb *PolyCreateBulk) OnConflictColumns(columns ...string) *PolyUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &PolyUpsertBulk{
		create: pcb,
	}
}

// PolyUpsertBulk is the builder for "upsert"-ing
// a bulk of Poly nodes.
type PolyUpsertBulk struct {
	create *PolyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Poly.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PolyUpsertBulk) UpdateNewValues() *PolyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(poly.FieldCode)
			}
			if _, exists := b.mutation.MallCode(); exists {
				s.SetIgnore(poly.FieldMallCode)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Poly.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PolyUpsertBulk) Ignore() *PolyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PolyUpsertBulk) DoNothing() *PolyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PolyCreateBulk.OnConflict
// documentation for more info.
func (u *PolyUpsertBulk) Update(set func(*PolyUpsert)) *PolyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PolyUpsert{UpdateSet: update})
	}))
	return u
}

// SetRuleCode sets the "rule_code" field.
func (u *PolyUpsertBulk) SetRuleCode(v string) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetRuleCode(v)
	})
}

// UpdateRuleCode sets the "rule_code" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateRuleCode() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateRuleCode()
	})
}

// SetName sets the "name" field.
func (u *PolyUpsertBulk) SetName(v string) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateName() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateName()
	})
}

// SetDesc sets the "desc" field.
func (u *PolyUpsertBulk) SetDesc(v string) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetDesc(v)
	})
}

// UpdateDesc sets the "desc" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateDesc() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateDesc()
	})
}

// SetStartTime sets the "start_time" field.
func (u *PolyUpsertBulk) SetStartTime(v time.Time) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateStartTime() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *PolyUpsertBulk) SetEndTime(v time.Time) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateEndTime() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateEndTime()
	})
}

// SetStatus sets the "status" field.
func (u *PolyUpsertBulk) SetStatus(v int) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *PolyUpsertBulk) AddStatus(v int) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateStatus() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateStatus()
	})
}

// SetType sets the "type" field.
func (u *PolyUpsertBulk) SetType(v int) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *PolyUpsertBulk) AddType(v int) *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *PolyUpsertBulk) UpdateType() *PolyUpsertBulk {
	return u.Update(func(s *PolyUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *PolyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PolyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PolyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PolyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
