// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/twiglab/crm/poly/orm/ent/poly"
	"github.com/twiglab/crm/poly/orm/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	polyMixin := schema.Poly{}.Mixin()
	polyMixinFields0 := polyMixin[0].Fields()
	_ = polyMixinFields0
	polyFields := schema.Poly{}.Fields()
	_ = polyFields
	// polyDescCreateTime is the schema descriptor for create_time field.
	polyDescCreateTime := polyMixinFields0[0].Descriptor()
	// poly.DefaultCreateTime holds the default value on creation for the create_time field.
	poly.DefaultCreateTime = polyDescCreateTime.Default.(func() time.Time)
	// polyDescUpdateTime is the schema descriptor for update_time field.
	polyDescUpdateTime := polyMixinFields0[1].Descriptor()
	// poly.DefaultUpdateTime holds the default value on creation for the update_time field.
	poly.DefaultUpdateTime = polyDescUpdateTime.Default.(func() time.Time)
	// poly.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	poly.UpdateDefaultUpdateTime = polyDescUpdateTime.UpdateDefault.(func() time.Time)
	// polyDescCode is the schema descriptor for code field.
	polyDescCode := polyFields[0].Descriptor()
	// poly.DefaultCode holds the default value on creation for the code field.
	poly.DefaultCode = polyDescCode.Default.(func() string)
	// poly.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	poly.CodeValidator = func() func(string) error {
		validators := polyDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// polyDescMallCode is the schema descriptor for mall_code field.
	polyDescMallCode := polyFields[1].Descriptor()
	// poly.MallCodeValidator is a validator for the "mall_code" field. It is called by the builders before save.
	poly.MallCodeValidator = func() func(string) error {
		validators := polyDescMallCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(mall_code string) error {
			for _, fn := range fns {
				if err := fn(mall_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// polyDescRule is the schema descriptor for rule field.
	polyDescRule := polyFields[2].Descriptor()
	// poly.RuleValidator is a validator for the "rule" field. It is called by the builders before save.
	poly.RuleValidator = func() func(string) error {
		validators := polyDescRule.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(rule string) error {
			for _, fn := range fns {
				if err := fn(rule); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// polyDescName is the schema descriptor for name field.
	polyDescName := polyFields[3].Descriptor()
	// poly.NameValidator is a validator for the "name" field. It is called by the builders before save.
	poly.NameValidator = func() func(string) error {
		validators := polyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// polyDescDesc is the schema descriptor for desc field.
	polyDescDesc := polyFields[4].Descriptor()
	// poly.DescValidator is a validator for the "desc" field. It is called by the builders before save.
	poly.DescValidator = polyDescDesc.Validators[0].(func(string) error)
	// polyDescStatus is the schema descriptor for status field.
	polyDescStatus := polyFields[7].Descriptor()
	// poly.DefaultStatus holds the default value on creation for the status field.
	poly.DefaultStatus = polyDescStatus.Default.(int32)
	// polyDescType is the schema descriptor for type field.
	polyDescType := polyFields[8].Descriptor()
	// poly.DefaultType holds the default value on creation for the type field.
	poly.DefaultType = polyDescType.Default.(int32)
}
