// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twiglab/crm/game/orm/ent/predicate"
	"github.com/twiglab/crm/game/orm/ent/usersignin"
)

// UserSignInQuery is the builder for querying UserSignIn entities.
type UserSignInQuery struct {
	config
	ctx        *QueryContext
	order      []usersignin.OrderOption
	inters     []Interceptor
	predicates []predicate.UserSignIn
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserSignInQuery builder.
func (usiq *UserSignInQuery) Where(ps ...predicate.UserSignIn) *UserSignInQuery {
	usiq.predicates = append(usiq.predicates, ps...)
	return usiq
}

// Limit the number of records to be returned by this query.
func (usiq *UserSignInQuery) Limit(limit int) *UserSignInQuery {
	usiq.ctx.Limit = &limit
	return usiq
}

// Offset to start from.
func (usiq *UserSignInQuery) Offset(offset int) *UserSignInQuery {
	usiq.ctx.Offset = &offset
	return usiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (usiq *UserSignInQuery) Unique(unique bool) *UserSignInQuery {
	usiq.ctx.Unique = &unique
	return usiq
}

// Order specifies how the records should be ordered.
func (usiq *UserSignInQuery) Order(o ...usersignin.OrderOption) *UserSignInQuery {
	usiq.order = append(usiq.order, o...)
	return usiq
}

// First returns the first UserSignIn entity from the query.
// Returns a *NotFoundError when no UserSignIn was found.
func (usiq *UserSignInQuery) First(ctx context.Context) (*UserSignIn, error) {
	nodes, err := usiq.Limit(1).All(setContextOp(ctx, usiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersignin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (usiq *UserSignInQuery) FirstX(ctx context.Context) *UserSignIn {
	node, err := usiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserSignIn ID from the query.
// Returns a *NotFoundError when no UserSignIn ID was found.
func (usiq *UserSignInQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = usiq.Limit(1).IDs(setContextOp(ctx, usiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersignin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (usiq *UserSignInQuery) FirstIDX(ctx context.Context) int {
	id, err := usiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserSignIn entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserSignIn entity is found.
// Returns a *NotFoundError when no UserSignIn entities are found.
func (usiq *UserSignInQuery) Only(ctx context.Context) (*UserSignIn, error) {
	nodes, err := usiq.Limit(2).All(setContextOp(ctx, usiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersignin.Label}
	default:
		return nil, &NotSingularError{usersignin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (usiq *UserSignInQuery) OnlyX(ctx context.Context) *UserSignIn {
	node, err := usiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserSignIn ID in the query.
// Returns a *NotSingularError when more than one UserSignIn ID is found.
// Returns a *NotFoundError when no entities are found.
func (usiq *UserSignInQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = usiq.Limit(2).IDs(setContextOp(ctx, usiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersignin.Label}
	default:
		err = &NotSingularError{usersignin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (usiq *UserSignInQuery) OnlyIDX(ctx context.Context) int {
	id, err := usiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserSignIns.
func (usiq *UserSignInQuery) All(ctx context.Context) ([]*UserSignIn, error) {
	ctx = setContextOp(ctx, usiq.ctx, ent.OpQueryAll)
	if err := usiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserSignIn, *UserSignInQuery]()
	return withInterceptors[[]*UserSignIn](ctx, usiq, qr, usiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (usiq *UserSignInQuery) AllX(ctx context.Context) []*UserSignIn {
	nodes, err := usiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserSignIn IDs.
func (usiq *UserSignInQuery) IDs(ctx context.Context) (ids []int, err error) {
	if usiq.ctx.Unique == nil && usiq.path != nil {
		usiq.Unique(true)
	}
	ctx = setContextOp(ctx, usiq.ctx, ent.OpQueryIDs)
	if err = usiq.Select(usersignin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (usiq *UserSignInQuery) IDsX(ctx context.Context) []int {
	ids, err := usiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (usiq *UserSignInQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, usiq.ctx, ent.OpQueryCount)
	if err := usiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, usiq, querierCount[*UserSignInQuery](), usiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (usiq *UserSignInQuery) CountX(ctx context.Context) int {
	count, err := usiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (usiq *UserSignInQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, usiq.ctx, ent.OpQueryExist)
	switch _, err := usiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (usiq *UserSignInQuery) ExistX(ctx context.Context) bool {
	exist, err := usiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserSignInQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (usiq *UserSignInQuery) Clone() *UserSignInQuery {
	if usiq == nil {
		return nil
	}
	return &UserSignInQuery{
		config:     usiq.config,
		ctx:        usiq.ctx.Clone(),
		order:      append([]usersignin.OrderOption{}, usiq.order...),
		inters:     append([]Interceptor{}, usiq.inters...),
		predicates: append([]predicate.UserSignIn{}, usiq.predicates...),
		// clone intermediate query.
		sql:  usiq.sql.Clone(),
		path: usiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserSignIn.Query().
//		GroupBy(usersignin.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (usiq *UserSignInQuery) GroupBy(field string, fields ...string) *UserSignInGroupBy {
	usiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserSignInGroupBy{build: usiq}
	grbuild.flds = &usiq.ctx.Fields
	grbuild.label = usersignin.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserSignIn.Query().
//		Select(usersignin.FieldUserID).
//		Scan(ctx, &v)
func (usiq *UserSignInQuery) Select(fields ...string) *UserSignInSelect {
	usiq.ctx.Fields = append(usiq.ctx.Fields, fields...)
	sbuild := &UserSignInSelect{UserSignInQuery: usiq}
	sbuild.label = usersignin.Label
	sbuild.flds, sbuild.scan = &usiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserSignInSelect configured with the given aggregations.
func (usiq *UserSignInQuery) Aggregate(fns ...AggregateFunc) *UserSignInSelect {
	return usiq.Select().Aggregate(fns...)
}

func (usiq *UserSignInQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range usiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, usiq); err != nil {
				return err
			}
		}
	}
	for _, f := range usiq.ctx.Fields {
		if !usersignin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if usiq.path != nil {
		prev, err := usiq.path(ctx)
		if err != nil {
			return err
		}
		usiq.sql = prev
	}
	return nil
}

func (usiq *UserSignInQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserSignIn, error) {
	var (
		nodes = []*UserSignIn{}
		_spec = usiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserSignIn).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserSignIn{config: usiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, usiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (usiq *UserSignInQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := usiq.querySpec()
	_spec.Node.Columns = usiq.ctx.Fields
	if len(usiq.ctx.Fields) > 0 {
		_spec.Unique = usiq.ctx.Unique != nil && *usiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, usiq.driver, _spec)
}

func (usiq *UserSignInQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usersignin.Table, usersignin.Columns, sqlgraph.NewFieldSpec(usersignin.FieldID, field.TypeInt))
	_spec.From = usiq.sql
	if unique := usiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if usiq.path != nil {
		_spec.Unique = true
	}
	if fields := usiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersignin.FieldID)
		for i := range fields {
			if fields[i] != usersignin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := usiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := usiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := usiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := usiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (usiq *UserSignInQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(usiq.driver.Dialect())
	t1 := builder.Table(usersignin.Table)
	columns := usiq.ctx.Fields
	if len(columns) == 0 {
		columns = usersignin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if usiq.sql != nil {
		selector = usiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if usiq.ctx.Unique != nil && *usiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range usiq.predicates {
		p(selector)
	}
	for _, p := range usiq.order {
		p(selector)
	}
	if offset := usiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := usiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserSignInGroupBy is the group-by builder for UserSignIn entities.
type UserSignInGroupBy struct {
	selector
	build *UserSignInQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (usigb *UserSignInGroupBy) Aggregate(fns ...AggregateFunc) *UserSignInGroupBy {
	usigb.fns = append(usigb.fns, fns...)
	return usigb
}

// Scan applies the selector query and scans the result into the given value.
func (usigb *UserSignInGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, usigb.build.ctx, ent.OpQueryGroupBy)
	if err := usigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserSignInQuery, *UserSignInGroupBy](ctx, usigb.build, usigb, usigb.build.inters, v)
}

func (usigb *UserSignInGroupBy) sqlScan(ctx context.Context, root *UserSignInQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(usigb.fns))
	for _, fn := range usigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*usigb.flds)+len(usigb.fns))
		for _, f := range *usigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*usigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserSignInSelect is the builder for selecting fields of UserSignIn entities.
type UserSignInSelect struct {
	*UserSignInQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (usis *UserSignInSelect) Aggregate(fns ...AggregateFunc) *UserSignInSelect {
	usis.fns = append(usis.fns, fns...)
	return usis
}

// Scan applies the selector query and scans the result into the given value.
func (usis *UserSignInSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, usis.ctx, ent.OpQuerySelect)
	if err := usis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserSignInQuery, *UserSignInSelect](ctx, usis.UserSignInQuery, usis, usis.inters, v)
}

func (usis *UserSignInSelect) sqlScan(ctx context.Context, root *UserSignInQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(usis.fns))
	for _, fn := range usis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*usis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
