services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      ALLOW_EMPTY_PASSWORD: true
      POSTGRESQL_USERNAME: 'postgres'
      POSTGRESQL_PASSWORD: 'erpPass123'
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:4.0
    restart: always
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      RABBITMQ_USERNAME: erp
      RABBITMQ_PASSWORD: erpPass123
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true

volumes:
  postgresql_data:
    driver: local
