// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package low

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/twiglab/crm/erp/pkg/shop"
)

// QryShopByCodeResponse is returned by QryShopByCode on success.
type QryShopByCodeResponse struct {
	QryShopByCode shop.ShopResp `json:"qryShopByCode"`
}

// GetQryShopByCode returns QryShopByCodeResponse.QryShopByCode, and is useful for accessing the field via an interface.
func (v *QryShopByCodeResponse) GetQryShopByCode() shop.ShopResp { return v.QryShopByCode }

// __QryShopByCodeInput is used internally by genqlient
type __QryShopByCodeInput struct {
	Input shop.QryShopReq `json:"input"`
}

// GetInput returns __QryShopByCodeInput.Input, and is useful for accessing the field via an interface.
func (v *__QryShopByCodeInput) GetInput() shop.QryShopReq { return v.Input }

// The query or mutation executed by QryShopByCode.
const QryShopByCode_Operation = `
query QryShopByCode ($input: QryShopReq!) {
	qryShopByCode(input: $input) {
		mallCode
		mallName
		pos
		floor
		shopCode
		shopName
		contractCode
		bizClass1
		bizClass2
		bizClassName1
		bizClassName2
		status
	}
}
`

func QryShopByCode(
	ctx_ context.Context,
	client_ graphql.Client,
	input shop.QryShopReq,
) (*QryShopByCodeResponse, error) {
	req_ := &graphql.Request{
		OpName: "QryShopByCode",
		Query:  QryShopByCode_Operation,
		Variables: &__QryShopByCodeInput{
			Input: input,
		},
	}
	var err_ error

	var data_ QryShopByCodeResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
