id: member

web: 
  addr: 0.0.0.0:10009

mq: 
  addr: amqp://erp:erpPass123@81.71.151.176:5672

db:
  dsn: user=crm password=cRm9ijn)OKM host=pipi.dev port=5432 database=crm sslmode=disable

bc-cli:
  rpc-url: http://127.0.0.1:100008/gqlrpc/query

member-cli:
  rpc-url: http://127.0.0.1:100009/gqlrpc/query
