// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson794297d0DecodeWxloginModel(in *jlexer.Lexer, out *AuthInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "JsCode":
			out.JsCode = string(in.String())
		case "WxOpenID":
			out.WxOpenID = string(in.String())
		case "AuthCode":
			out.AuthCode = string(in.String())
		case "Code":
			out.Code = string(in.String())
		case "PhoneNo":
			out.PhoneNo = string(in.String())
		case "UID":
			out.UID = string(in.String())
		case "Ts":
			out.Ts = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson794297d0EncodeWxloginModel(out *jwriter.Writer, in AuthInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"JsCode\":"
		out.RawString(prefix[1:])
		out.String(string(in.JsCode))
	}
	{
		const prefix string = ",\"WxOpenID\":"
		out.RawString(prefix)
		out.String(string(in.WxOpenID))
	}
	{
		const prefix string = ",\"AuthCode\":"
		out.RawString(prefix)
		out.String(string(in.AuthCode))
	}
	{
		const prefix string = ",\"Code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"PhoneNo\":"
		out.RawString(prefix)
		out.String(string(in.PhoneNo))
	}
	{
		const prefix string = ",\"UID\":"
		out.RawString(prefix)
		out.String(string(in.UID))
	}
	{
		const prefix string = ",\"Ts\":"
		out.RawString(prefix)
		out.Int64(int64(in.Ts))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson794297d0EncodeWxloginModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson794297d0EncodeWxloginModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson794297d0DecodeWxloginModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson794297d0DecodeWxloginModel(l, v)
}
